CREATE TABLE IF NOT EXISTS STUDENTS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    age INTEGER
);